### ISSUE TITLE
So far unhandled FLAG: 163. Please update UMI-Bam

### ISSUE THREAD

**Issue by rmvpaeme** [FelixKrueger/Umi-Grinder#1]
Hi Felix,

I'm getting the error `"So far unhandled FLAG: 163. Please update UMI-Bam"`, when I run:
`UmiBam --double_umi input_pe.bam` (mapped output file from bismark).

I tried looking into `deduplicate_bismark`, but this doesn't support the `--double-umi` flag.

Any suggestions?

**Comment by FelixKrueger** [comment]
This is odd, it seems to be running fine over here, and I have just checked a run from earlier this week and it did contain the FLAG 163... I have just updated to the latest version, could you try to clone the latest dev version and see if the just goes away magically?

**Comment by rmvpaeme** [comment]
Hi Felix,

Sorry for the late reply.
I updated UmiBam, but the issue remained. In certain setups also FLAG 147 instead of FLAG 163 was called, but stating the same error message.

It runs without any issues when I do `UmiBam -s input_pe.bam`.

**Comment by FelixKrueger** [comment]
Would you mind sending me a small sample of your file via email to felix.krueger@babraham.ac.uk?

**Comment by FelixKrueger** [comment]
Closing this as it appears to have gone somewhat stale.
